---
title: "RWorksheet_Siatan#3a"
author: "Floreda Mae Siatan"
date: "2022-10-22"
output: pdf_document
---




```{r vector1a}
first <- LETTERS [1:11]
first
```
```{r vector1b}
odd_nums <- LETTERS[seq (1,26,2)] 
odd_nums
```
```{r vector1c}
vowels <- LETTERS [c (1, 5, 9, 15, 21)]
vowels
```
```{r vector1d}
lower <- letters
lower [22:26]
```
```{r vector1e}
let <- letters [16:23]
let
```
```{r vector2a}
city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")
city

```
```{r vector2b}
temp <- c(42, 39, 34, 34, 30, 27)
temp

```
```{r vector2c}
city_temp <- cbind (c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City"),
                    c(42, 39, 34, 34, 30, 27))
city_temp
colnames(city_temp) <-c ("city", "temp")
city_temp
```
```{r vector2d}
city_temp [5]
city_temp [6]

```
```{r vector2e}
num_m <- matrix (c(1:8, 11:14), nrow=3, ncol=4)
num_m

```
```{r vector2f}
mul <- matrix(c(1:8, 11:14), nrow = 3, ncol = 4)
mul <- mul*2
mul

```
```{r vector2g}
mul[2,]

```
```{r vector2h}
mul[1, 3]

```
```{r vector2i}
mul [2,4]

```
```{r vector2j}
mul [3,2]

```
```{r vector2k}
mul [3,3]

```
```{r vector2l}
mul[,4]

```
```{r vector2m}
dimnames(mul) <- list(c("isa", "dalawa", "tatlo"), 
                     c("uno", "dos", "tres", "quatro"))
mul

```
```{r vector2n}
dim(num_m) <- c(6, 2) 
num_m

```
```{r vector2o}
num <- c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1)
  
num_array <- array(rep(num, 2), dim = c(2,4,3))
num_array

```
```{r vector2p}
3
```

















































































