---
title: "RWorksheet_Siatan#6"
author: "Floreda Mae Siatan"
date: "2022-12-1"
output:
  pdf_document: default
  word_document: default
---
```{r, vector = TRUE}
library(dplyr)
library(ggplot2)
library(tinytex)
```

```{r vector1}
data(mpg)
data_set <- as.data.frame(mpg)
nrow(mpg)
ncol(mpg)

```

```{r vector2}
mostModel <- data_set %>% group_by(manufacturer) %>% count()
mostModel
colnames(mostModel) <- c("Manufacturer","Counts")
mostModel
```

```{r vector3}
mostVariation<- data_set %>% group_by(model) %>% count()
mostVariation
colnames(mostVariation) <- c("Model","Counts")
mostVariation
```

```{r vector4}
UniqueModel <- data_set %>% group_by(manufacturer, model) %>% distinct() %>% count()
UniqueModel
colnames(UniqueModel) <- c("Manufacturer", "Model","Counts")
UniqueModel

```

```{r vector5}
plot(UniqueModel)
ggplot(UniqueModel, aes(x = Model, y = Counts )) + geom_point(color='green')
```

```{r vector6}
ggplot(UniqueModel, aes(x = Model, y = Manufacturer )) + geom_point(color='green')
```

```{r vector7}
ggplot(mpg, aes(model, manufacturer)) + geom_point()
```


```{r vector8}
carsmodel <- data_set %>% group_by(model) %>% count()
carsmodel
colnames(carsmodel) <- c("Model","Counts")
carsmodel
```


```{r vector9}
qplot(model,data = mpg,main = "Number of Cars per Model", xlab = "Model",
      ylab = "Number of Cars", geom = "bar", fill = manufacturer) +
  coord_flip()

```

```{r vector10}
del <- carsmodel[1:20,] %>% top_n(2)
del
```


```{r vector11}
ggplot(mpg, aes(x = displ , y = cyl, col = displ )) + geom_point()

ggplot( data = mpg) +
  geom_point(mapping = aes(x = displ , y = cyl, col = displ))

ggplot(data = mpg, mapping = aes(x = displ, y = cyl)) +
  geom_point(mapping=aes(color=displ))
```


```{r vector12}
wheel_drive <- subset(mpg, drv == 'f')
wheel_drive <- nrow(wheel_drive)
wheel_drive
```


```{r vector13}
rearwheel <- subset(mpg, drv == 'r')
nrow(rearwheel)
rearwheel
```


```{r vector14}
num4 <- subset(mpg, drv == '4')
nrow(num4)
num4

```


```{r vector15}
c <- subset(mpg, class == 'compact')
nrow(c)
c

```


```{r vector16}
m_size <- subset(mpg, class == 'midsize')

nrow(m_size)
m_size
```

```{r vector17}
two_seater <- subset(mpg, class == '2seater')
nrow(two_seater)
two_seater

```


```{r vector18}
mini_van <- subset(mpg, class == 'minivan')
nrow(mini_van)
mini_van
```


```{r vector19}
p_u <- subset(mpg, class == 'pickup')
nrow(p_u)
p_u
```


```{r vector20}
sub_comp <- subset(mpg, class == 'subcompact')
nrow(sub_comp)
sub_comp
```


```{r vector21}
ggplot(mpg, aes(drv, class)) +
  geom_tile (aes(fill = class)) 
```

```{r vector22}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, colour = "blue"))

```

```{r vector23}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy), colour = "blue")

```

```{r vector24}
ggplot( data = mpg) +
  geom_point(mapping = aes(x = displ , y = hwy, col = displ)) 
```

```{r vector25}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point(mapping=aes(color=displ)) +
  geom_smooth(se =FALSE)

```

```{r vector26}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point(mapping=aes(color=displ)) +
  geom_smooth(se =FALSE,method = lm)
```

