---
title: "RWorksheet_Siatan#4"
author: "Floreda Mae Siatan"
date: "2022-11-22"
output: pdf_document
---

```{r vector1a}
ShoeSize <- c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5)

ShoeSize1 <-c (13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 8.5, 10.5, 11.0, 9.0, 13.0)

Height <- c(66.0,68.0,64.5,65.0,70.0,64.0,70.0,71.0,72.0,64.0,74.5,67.0,71.0,71.0)

Height1 <-c (77.0,72.0,59.0,62.0,72.0,66.0,64.0,67.0,73.0,69.0,72.0,70.0, 69.0,70.0)

Gender <- c("F", "F", "F", "F", "M", "F", "F", "F", "M", "F", "M", "F", "M", "M")
Gender1 <-c ("M", "M", "F", "F", "M", "F", "F", "M", "M", "F", "M", "M", "M", "M")

ShoeData <- data.frame (ShoeSize, Height, Gender, ShoeSize1, Height1, Gender1)

```


```{r vector1b}
m_shoesize <- cbind(ShoeSize,ShoeSize1)
m_shoesize

mean(m_shoesize)
```
```{r vector1.1b}
m_height <- cbind(Height, Height1)
m_height

mean(m_height)
```

``` {r vector 1c}
 #c. Is there a relationship between shoe size and height? Why?
        
      #Yes, especially for the data of male repondents, when the height is increased the shoesize also increase. But it does not apply to all, in female's data 
      #their shoesize varies.
```

```{r vector 2a}
months <- c("March","April","January","November","January","September","October","September","November","August","January","November","November","February","May","August",
"July","December","August","August","September","November","February","April")

```

``` {r vector 2b}
factor_months <- factor(months)
factor_months
```

``` {r vector 2c}
factor_months_vector <- factor_months
factor_months_vector
```
``` {r vector 2d}
summary(factor_months)
summary(factor_months_vector)
```       


``` {r vector 4a}
Direction <-c("East", "West", "North")
Direction
        
Frequency <-c(1, 4, 3)
Frequency
```

``` {r vector 4b}
tab <- data.frame(Direction, Frequency)
tab

factorS <- factor(Direction)

new_order_data <- factor(factorS,levels = c("East","West","North"))
print(new_order_data)
```
``` {r vector 4c}
setwd("C:/Users/Floreda/OneDrive/Documents")
getwd()

exdata <- read.table("import_march.csv", sep=",", header=TRUE, stringsAsFactor=FALSE);
exdata
```

``` {r vector 4d}
View(exdata)
```






