---
title: "SIATAN-Individual-Project2"
author: "Floreda Mae Siatan"
date: "2022-12-22"
output:
  html_document: default
  pdf_document: default
---

```{r packagesExtension}

library(wordcloud)
library(plotly)
library(tm)
library(dplyr)
library(RColorBrewer)
library(ggplot2)
library(twitteR)

```

```{r token}
CONSUMER_SECRET <- "m7YDTdIUsXrHBctdYXRL5vh8fXlVRPcOIYVmrK7z7fMddyuUFC"
CONSUMER_KEY <- "GkDEUOHWT25PLk78NjGpAlIY7"
ACCESS_SECRET <- "MA1Le3foaizXx6P8rlQc72axfUdsyITDajVJUYdykJrNX"
ACCESS_TOKEN <- "1320378136396091392-C2qoI175v2JLG3vEAV3gKRBtPiw9J6"
```

```{r setup}
setup_twitter_oauth(consumer_key = CONSUMER_KEY,
                    consumer_secret = CONSUMER_SECRET,
                    access_token = ACCESS_TOKEN,
                    access_secret = ACCESS_SECRET)
```

```{r trend}
avatar_trend = searchTwitter("AVATAR", n = 10000, 
                             since = "2022-12-19",
                             until = "2022-12-22",
                             lang = "en", 
                             retryOnRateLimit = 120)
avatar_trend
```

```{r avatardf}
tweetsDF <- twListToDF(avatar_trend)
tweetsDF
```


```{r saveload}
save(tweetsDF,file = "trendingTweetsDF.Rdata")
load(file = "trendingTweetsDF.Rdata")

```


```{r checking}
data_checking <- sapply(avatar_trend,
                function(x) sum(is.na(x)))  
data_checking 
```

```{r subset}
tweet <- tweetsDF %>%
  select(screenName,text,created, isRetweet) %>% filter(isRetweet == FALSE)
tweet
```


```{r grouping}
tweet %>% group_by(1) %>%  
  summarise(max = max(created),
  min = min(created))



```
```{r create}
create_data <- tweet %>%  mutate(Created_At_Round = created %>% round(units = 'hours') %>% as.POSIXct())
create_data
```
```{r minmax}
minim <- tweet %>% pull(created) %>% min()
minim 

maxim <- tweet %>% pull(created) %>% max()
maxim
```


```{r plot}
plotdata <- ggplot(create_data,
            aes(x = Created_At_Round)) +
            geom_histogram(aes(fill = ..count..)) +
            theme(legend.position = "right") +
             xlab("Time") + ylab("Number of tweets") + 
            scale_fill_gradient(low = "yellow", high = "blue")

plotdata %>% ggplotly()
```


```{r retweets}
sub_tweets <- tweetsDF %>%
              select(screenName,text,created, isRetweet) %>% filter(isRetweet == FALSE)

sub_tweets
```


```{r groupretweets}
sub_tweets %>%  
  group_by(1) %>%  
  summarise(max = max(created), min = min(created))

create <- sub_tweets %>%  mutate(Created_At_Round = created %>% round(units = 'hours') %>% as.POSIXct())
create

mini <- sub_tweets %>% pull(created) %>% min()
mini

maxi <- sub_tweets %>% pull(created) %>% max()
maxi
```


```{r replot}
plot_data <- ggplot(create, aes(x = Created_At_Round)) +
  geom_histogram(aes(fill = ..count..)) +
  theme(legend.position = "right") +
  xlab("Time") + ylab("Number of tweets") + 
  scale_fill_gradient(low = "blue", high = "red")

plot_data %>% ggplotly()
```
